#!groovy

// Generated by IBM TransformationAdvisor
// Mon May 06 18:05:13 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}